import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css'
import Link from 'next/link'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="container">
          <div className="row">
            <div className="text-uppercase text-center h1 pt-3"><h1>Vercel - Home Assignment</h1></div>
          </div>
          <div className="row"><Link href="/">Home</Link></div>
          <div className="row mt-3">
            <div className="col-sm-3 bg-light border p-5">
              <h2 className="text-capitalize h3">Questions</h2>
              <ul>
                <li className="p-2"><Link href="/question/q1">Question 1</Link></li>
                <li className="p-2"><Link href="/question/q2">Question 2</Link></li>
                <li className="p-2"><Link href="/question/q3">Question 3</Link></li>
                <li className="p-2"><Link href="/question/q4">Question 4</Link></li>
                <li className="p-2"><Link href="/question/q5">Question 5</Link></li>
                <li className="p-2"><Link href="/question/q6">Question 6</Link></li>
                <li className="p-2"><Link href="/question/q7">Question 7</Link></li>
                <li className="p-2"><Link href="/question/q8">Question 8</Link></li>
                <li className="p-2"><Link href="/question/q9">Question 9</Link></li>
                <li className="p-2"><Link href="/question/q10">Question 10</Link></li>
              </ul>
            </div>
            <div className="col-sm-9 bg-light border p-5">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
